// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SocialMedia.API.Data;

#nullable disable

namespace jobapplicationmanagementsystemapi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240627071232_UpdateJobApplicationTable3")]
    partial class UpdateJobApplicationTable3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SocialMedia.API.Models.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserID"));

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Fullname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserID");

                    b.ToTable("User");
                });

            modelBuilder.Entity("job_application_management_system_api.Models.Job", b =>
                {
                    b.Property<int>("JobID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("JobID"));

                    b.Property<string>("Applicants")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Deadline")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Designation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JobTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JobType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaxApplicants")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Negotiable")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostedOn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Salary")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WorkHourEnd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WorkHourStart")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("JobID");

                    b.ToTable("Job");
                });

            modelBuilder.Entity("job_application_management_system_api.Models.JobApplication", b =>
                {
                    b.Property<int>("JobApplicationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("JobApplicationID"));

                    b.Property<string>("BscAIUB")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BscAIUBID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BscAdmissionDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BscCGPA")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BscGraduate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BscGraduationDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BscStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BscUniversity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CoverLetter")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CurrentAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cv")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FathersName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("JobID")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MothersName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MscAIUB")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MscAIUBID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MscAdmissionDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MscCGPA")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MscGraduate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MscGraduationDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MscStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MscUniversity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PermanentAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("JobApplicationID");

                    b.ToTable("JobApplication");
                });

            modelBuilder.Entity("job_application_management_system_api.Models.JobRequirement", b =>
                {
                    b.Property<int>("JobRequirementID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("JobRequirementID"));

                    b.Property<int>("JobID")
                        .HasColumnType("int");

                    b.Property<string>("Requirement")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("JobRequirementID");

                    b.ToTable("JobRequirement");
                });

            modelBuilder.Entity("job_application_management_system_api.Models.JobResponsibility", b =>
                {
                    b.Property<int>("JobResponsibilityID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("JobResponsibilityID"));

                    b.Property<int>("JobID")
                        .HasColumnType("int");

                    b.Property<string>("Responsibility")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("JobResponsibilityID");

                    b.ToTable("JobResponsibility");
                });

            modelBuilder.Entity("job_application_management_system_api.Models.UserSkill", b =>
                {
                    b.Property<int>("UserSkillID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserSkillID"));

                    b.Property<int>("JobApplicationID")
                        .HasColumnType("int");

                    b.Property<string>("Skill")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserSkillID");

                    b.ToTable("UserSkill");
                });
#pragma warning restore 612, 618
        }
    }
}
